name: bias-bench
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - accelerate=0.33.0
  - aiofiles=23.2.1
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - annotated-types=0.7.0
  - anyio=4.9.0
  - arrow=1.3.0
  - async-timeout=4.0.3
  - attrs=24.1.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.14
  - aws-c-common=0.9.19
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.8
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.9
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.9
  - aws-sdk-cpp=1.11.329
  - binaryornot=0.4.4
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.32.3
  - ca-certificates=2025.4.26
  - certifi=2025.4.26
  - cffi=1.16.0
  - chardet=5.2.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - cookiecutter=2.6.0
  - cuda-cudart=12.4.99
  - cuda-cudart_linux-64=12.4.99
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.0
  - cuda-nvrtc=12.4.99
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.99
  - cuda-runtime=12.4.0
  - cuda-version=12.4
  - cycler=0.12.1
  - datasets=2.20.0
  - dill=0.3.8
  - dnspython=2.7.0
  - email-validator=2.2.0
  - email_validator=2.2.0
  - evaluate=0.4.3
  - exceptiongroup=1.2.2
  - fastapi=0.115.7
  - fastapi-cli=0.0.7
  - ffmpeg=4.3
  - ffmpy=0.3.0
  - filelock=3.15.4
  - fonttools=4.53.1
  - freetype=2.10.4
  - frozenlist=1.4.1
  - fsspec=2024.5.0
  - gflags=2.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gnutls=3.6.13
  - gradio=4.44.1
  - gradio-client=1.3.0
  - h11=0.16.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.9
  - httptools=0.6.4
  - httpx=0.28.1
  - huggingface_hub=0.24.5
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.7
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - intel-openmp=2023.1.0
  - jbig=2.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=2.2.1
  - libabseil=20240116.2
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcublas=12.4.2.65
  - libcufft=11.2.0.44
  - libcufile=1.9.0.20
  - libcurand=10.3.5.119
  - libcurl=8.8.0
  - libcusolver=11.6.0.99
  - libcusparse=12.3.0.142
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgomp=14.1.0
  - libgoogle-cloud=2.24.0
  - libgoogle-cloud-storage=2.24.0
  - libgrpc=1.62.2
  - libhwloc=2.11.1
  - libiconv=1.17
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libnpp=12.2.5.2
  - libnvfatbin=12.4.99
  - libnvjitlink=12.4.99
  - libnvjpeg=12.3.1.89
  - libparquet=16.1.0
  - libpng=1.6.37
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libssh2=1.11.0
  - libstdcxx-ng=14.1.0
  - libthrift=0.19.0
  - libtiff=4.3.0
  - libutf8proc=2.8.0
  - libuv=1.48.0
  - libwebp-base=1.4.0
  - libxml2=2.13.1
  - libzlib=1.2.13
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib-base=3.5.2
  - mdurl=0.1.2
  - mkl=2023.1.0
  - mpmath=1.3.0
  - multidict=6.0.5
  - multiprocess=0.70.16
  - munkres=1.1.4
  - ncurses=6.4
  - nettle=3.6
  - networkx=3.2.1
  - nltk=3.8.1
  - numpy=1.26.4
  - ocl-icd=2.3.2
  - olefile=0.47
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.3.1
  - orc=2.0.1
  - orjson=3.10.7
  - packaging=24.1
  - pandas=2.2.2
  - pillow=8.2.0
  - pip=24.0
  - psutil=6.0.0
  - pyarrow=16.1.0
  - pyarrow-core=16.1.0
  - pyarrow-hotfix=0.6
  - pycparser=2.22
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pydub=0.25.1
  - pygments=2.19.1
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.9.19
  - python-dateutil=2.9.0
  - python-dotenv=1.1.0
  - python-multipart=0.0.20
  - python-slugify=8.0.4
  - python-tzdata=2024.1
  - python-xxhash=3.4.1
  - python_abi=3.9
  - pytorch=2.4.0
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - re2=2023.09.01
  - readline=8.2
  - regex=2024.7.24
  - requests=2.32.3
  - rich=14.0.0
  - rich-toolkit=0.11.3
  - ruff=0.6.2
  - s2n=1.4.15
  - safetensors=0.4.3
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - semantic_version=2.10.0
  - setuptools=72.1.0
  - shellingham=1.5.4
  - six=1.16.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - sqlite=3.45.3
  - starlette=0.45.3
  - sympy=1.13.0
  - tabulate=0.9.0
  - tbb=2021.12.0
  - text-unidecode=1.3
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tokenizers=0.19.1
  - tomlkit=0.12.0
  - torchaudio=2.4.0
  - torchtriton=3.0.0
  - torchvision=0.19.0
  - tqdm=4.66.5
  - transformers=4.43.3
  - typer=0.15.3
  - typer-slim=0.15.3
  - typer-slim-standard=0.15.3
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - uvicorn=0.34.2
  - uvicorn-standard=0.34.2
  - uvloop=0.21.0
  - watchfiles=0.23.0
  - websockets=12.0
  - wheel=0.43.0
  - xxhash=0.8.2
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.6
  - pip:
      - altair==5.5.0
      - astor==0.8.1
      - base58==2.1.1
      - black==21.12b0
      - blinker==1.9.0
      - cachetools==5.5.2
      - click==7.1.2
      - flake8==7.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - inflate64==1.0.1
      - iniconfig==2.1.0
      - isort==5.8.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - mccabe==0.7.0
      - multivolumefile==0.2.3
      - mypy-extensions==1.1.0
      - narwhals==1.38.0
      - pathspec==0.12.1
      - platformdirs==4.3.7
      - plotly==6.0.1
      - pluggy==1.5.0
      - promptsource==0.2.3
      - protobuf==6.30.2
      - py7zr==0.22.0
      - pybcj==1.0.6
      - pycodestyle==2.13.0
      - pycryptodomex==3.22.0
      - pydeck==0.9.1
      - pyflakes==3.3.2
      - pyppmd==1.1.1
      - pytest==8.3.5
      - pyzstd==0.16.2
      - referencing==0.36.2
      - rpds-py==0.24.0
      - smmap==5.0.2
      - streamlit==0.82.0
      - texttable==1.7.0
      - toml==0.10.2
      - tomli==1.2.3
      - tornado==6.4.2
      - tzlocal==5.3.1
      - validators==0.35.0
      - watchdog==6.0.0